### ISSUE TITLE
Can not compile - neither AUR nor manually

### ISSUE THREAD

**Issue by Flyxi121** [fluix-dev/sway-borders#26]
If you need more details please tell me what you need, I'm kind of unexperienced in writing issues. 
I'm sitting on the newest packages releases in arch but i could not figure out which package is causing problems. I tried to roll back to the package versions from two weeks ago where i still had sway-borders installed, uninstalled it and tried to reinstall, but it was not working. Now I tried in a fresh VM but still no success.

`meson -v: 0.56.2`
`ninja --version: 1.10.2`

Down below is the output of `ninja -C build`. I figured that pasting the output in here without external formatting would not really be readable. I figured that I could provide the `yay -S sway-borders-git` output as well.
[ninja-output.txt](https://github.com/fluix-dev/sway-borders/files/5833116/output.txt)
[aur-output.txt](https://github.com/fluix-dev/sway-borders/files/5833153/aur-output.txt)

**Comment by fluix-dev** [comment]
Just pulled Sway upstream, can you try now?

**Comment by Flyxi121** [comment]
Working like a charm! Thanks a lot!
