### ISSUE TITLE
Unable to get Sway-borders to work

### ISSUE THREAD

**Issue by 0reoKing** [fluix-dev/sway-borders#27]
OS: Fedora 33
I have tryed to compile sway-borders but it said that my version of wlroots is too old so I compiled wlroots from source and now sway-borders is compiling however when I type in sway I get this: 
sway: error while loading shared libraries: libwlroots.so.7: cannot open shared object file: No such file or directory

**Comment by fluix-dev** [comment]
Have you installed wlroots `sudo ninja -C build install`?

**Comment by 0reoKing** [comment]
> Have you installed wlroots `sudo ninja -C build install`?

yes I did

**Comment by 0reoKing** [comment]
Perhaps I did not install sway-borders and wlroots properly and maybe I should uninstall them and reinstall any idea on how to do this?

**Comment by fluix-dev** [comment]
Perhaps try [this](https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject), cloning this repo instead of upstream?

**Comment by 0reoKing** [comment]
ok

**Comment by 0reoKing** [comment]
> Perhaps try [this](https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject), cloning this repo instead of upstream?

Ok it is working now

**Comment by fluix-dev** [comment]
Sounds good, enjoy!

**Comment by 0reoKing** [comment]
however I dont want to manually launch it from that dir every time any idea on how to make it launch with just the command `sway`

**Comment by fluix-dev** [comment]
`sudo ninja -C build install`?
