### ISSUE TITLE
Waybar delay in launch

### ISSUE THREAD

**Issue by kushraj** [fluix-dev/sway-borders#28]
### Please fill out the following:
**Sway Version:**
  sway version 1.5-e9fa9821 (Jan 31 2021, branch 'master')

**Debug Log:**
[sway.log](https://gist.github.com/kushraj/ed013ed25da5f5e17095b1555b41a2c0)

**Configuration File:**
[config](https://gist.github.com/kushraj/e14fa96fc27901dc93378ae2b6f646c4)

**Problem**
waybar, both git and release version ) taking almost 25 seconds to reload, on default and current config. On reloading sway, bar disappears and comes back after ~25 seconds with/out default ( none ) config

Here's the waybar [log](https://gist.github.com/kushraj/adc57c0276356a8a877babb34976422f) if it helps
No such issue in sway-git upstream

To check, I installed sway-borders after removing sway, and weirdly it didn't start after quiting sway, but only after a restart

**Comment by fluix-dev** [comment]
Overall, this seems like [this issue](https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start) but then I'm not sure why it would occur on sway-borders and not sway. I don't know much about D-Bus in general, but perhaps it had already started beforehand and not with sway-borders? I'm not sure, but please try the fix.

---

If the above doesn't fix it, I can't think of anything that would cause this that is specific to sway-borders. It _really does_ just render some extra textures and I use waybar myself just fine. Can you try the following to make sure I can get clear reproduction steps:
 - Comment out all the `border_images` in your config
 - Install sway from git
 - Reboot
 - Run sway (see what happens, also take a log)
 - Exit sway
 - Reboot
 - Run sway-borders (see what happens, also take a log)
 - Exit sway-borders

Let me know if they act differently and post the logs so I can compare.

**Comment by kushraj** [comment]
Well yeah, that did solve the problem, albeit after a restart. thanks for the help
you still need the logs ?

**Comment by fluix-dev** [comment]
I actually just experienced this for the first time today -- something that has never happened before. Maybe some update broke _something_, I'm not really sure. Send the logs because it wouldn't hurt though I doubt I could really do anything. Thanks for checking though!

**Comment by p00f** [comment]
gtkgreet also takes a lot of time to load the login screen (it uses its own sway session and kills it on login)

**Comment by fluix-dev** [comment]
Yeah, I really don't think this has anything specific to do with this fork.

**Comment by p00f** [comment]
switching to sway stable fixes both of these for me

**Comment by fluix-dev** [comment]
Are you using the AUR package? If so, can you try placing [this file](https://aur.archlinux.org/cgit/aur.git/plain/50-systemd-user.conf?h=sway-git) into `/etc/sway/config.d/` as is done by `sway-git` [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sway-git#n64).

**Comment by p00f** [comment]
it's already there

**Comment by p00f** [comment]
yeah that fixes
btw the latest update doesn't build, it says
https://github.com/fluix-dev/sway-borders/blob/076618c635f93d9b4ca54089d7895bd75bb614b8/sway/input/text_input.c#L102 should be v3 instead of V3

**Comment by fluix-dev** [comment]
Alright, I'll add that to the PKGBUILD and report back. The `V3` [is correct](https://github.com/swaywm/sway/blob/4e02a598a33fb9b306a1ab220438adf82cac07a6/sway/input/text_input.c#L102), you need to update wlroots.

**Comment by fluix-dev** [comment]
[Done.](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=sway-borders-git&id=0e35011c44cc5b29c7dd36dc7df365c99f93f6a8) Apologies for taking a while.
