### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by caughtquick** [fluix-dev/sway-borders#30]
Implement rounded corners into sway. The sway devs have said they don't have interest in maintaining the code even if it was made fully functional via a PR. Could be used for making everything look better

**Comment by fluix-dev** [comment]
You _can_ have rounded borders, you just need to create your own images. See [here](https://github.com/fluix-dev/sway-borders/tree/master/contrib/borders) for examples.

I assume your request is to add a config options like `border_radius <px>`, which I will be working on as I redesign everything to use shaders.
