### ISSUE TITLE
Titles and borders not showing up with latest master & wlroots master?

### ISSUE THREAD

**Issue by GorrillaRibs** [fluix-dev/sway-borders#32]
- **Sway Version:**
sway version 1.5-3a4ee603 (Feb 27 2021, branch 'makepkg')

- **Debug Log:**
[Debug Log](https://gist.github.com/GorrillaRibs/a7d9ee79c6c87cd3f1d36d8c91f82712)
There's a bunch of errors with wlr's render/gles2/texture.c (Unsupported pixel format?)

- **Configuration File:**
https://gist.github.com/GorrillaRibs/278a5ea0a882f344af54467475f92d82

- **Description:**
Seems to be related to the latest git master of wlroots, it started in [this commit](https://github.com/swaywm/wlroots/commit/27fba3df4347df65fbb8b0781ae407e410ef458b) and was fixed in regular sway in [this commit](https://github.com/swaywm/wlroots/commit/c2815fd44de5d74e379c118b4ccded5a9419e32c), but titles and borders still don't show up here. Seems related to a change to use a drm format?

Let me know if there's anything else I can do to help!

**Comment by GorrillaRibs** [comment]
An addition, [this](https://github.com/swaywm/wlroots/issues/2757) issue in wlroots proper  has a couple screenshots & a video which might be useful.

**Comment by GorrillaRibs** [comment]
Another addition, building with this attached patch (which just changes WL_SHM_FORMAT's to DRM_FORMAT's as upstream sway did for the other thing, which gets titles back, but no borders are being shown. The errors are gone from the log though, new log [here](https://gist.github.com/GorrillaRibs/16cf6d5708621f2d200c0e75941d0a8f) - nothing jumps out at me as being related to borders, though.


I also just realized I could've edited my original message for all this, sorry

**Comment by fluix-dev** [comment]
Wow, thanks for doing everything! Pushed 7f4a3e0ebe906aff14043547ce4b529f97f0fe53
