### ISSUE TITLE
Creating a tabbed layout (mod+w by default) on a new workspace crashes sway

### ISSUE THREAD

**Issue by GorrillaRibs** [fluix-dev/sway-borders#33]
- **Sway Version:**
- sway version 1.5-88b86ea3 (Mar 15 2021, branch 'master')

- **Debug Log:**
- https://gist.github.com/GorrillaRibs/b00c7a103b2fe73ce72944ad0dc929ec

- **Configuration File:**
- https://gist.github.com/GorrillaRibs/f6d815cbc29ec07492b5f43b063982a2

- **Stack Trace:**
- https://gist.github.com/GorrillaRibs/758b34f5b6d18e09dab885b4b7e441aa

- **Description:**
  - Start sway, press mod+w to do a tabbed layout (or on a new workspace, without opening other windows)

Doesn't seem to happen on the latest sway upstream, with the same wlroots version. Maybe related to trying to draw borders on a container that isn't there?

If there's anything else I can do to help debug let me know!

edit: clarified it doesn't happen in regular sway

**Comment by GorrillaRibs** [comment]
So I finally got around to taking a proper look at this - debugging when it dies shows the crash seems to happen in `container_find_child `in sway/tree/container.c - specifically, it crashed on 
```
if (!container->pending.children) {
    return NULL;
}
```
gonna investigate further, hopefully with exactly where  it crashes I can work out a fix

**Comment by GorrillaRibs** [comment]
Update - the crash _actually_ happens due to `render_border_textures_for_workspace `in desktop/render.c - specifically when it's called from `render_workspace` (I think that's the only time it's called), so now I've just got to figure out why it crashes now that I know where it is.

**Comment by GorrillaRibs** [comment]
...And fixed! It was only a couple lines to fix, just adding an early return from render_border_textures_for_workspace in case no window was there fixed it - patch below here, but I can make a proper merge request if that's easier for ya.

```

From f8808afb27582201cf5432ba7d1d65b5313ed4ef Mon Sep 17 00:00:00 2001
From: Robert Miller <legomaster57@gmail.com>
Date: Sun, 4 Apr 2021 19:27:14 -0400
Subject: [PATCH] fix tabbed layout crash

---
 sway/desktop/render.c | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/sway/desktop/render.c b/sway/desktop/render.c
index 256ac298..988ca803 100644
--- a/sway/desktop/render.c
+++ b/sway/desktop/render.c
@@ -906,6 +906,9 @@ static void render_border_textures_for_workspace(struct sway_output *output,
 		workspace_get_box(ws, &box);
 
 		struct sway_container *con = ws->tiling->items[0];
+		if (ws->tiling->length == 0) {
+			return;
+		}
 		struct border_textures *textures = get_border_textures_for_container(con);
 		render_border_textures(output, damage, &box, textures->texture, con->alpha);
 	}
-- 
2.31.1


```

**Comment by fluix-dev** [comment]
Thanks so much @GorrillaRibs! I saw the same thing you saw but didn't have time to go from there.

Pushed https://github.com/fluix-dev/sway-borders/commit/9178e17937e2fe062e43739f9789e83aa727b761
