### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Ziiga** [fluix-dev/sway-borders#36]
Encountering an error when trying to compile Sway-borders. The same error occurs when building manually and when using the AUR.

Bellow is the output of both `ninja -C build` and `paru -S sway-borders-git`:
[ninja-output.txt](https://github.com/fluix-dev/sway-borders/files/6658997/ninja-output.txt)
[paru-output.txt](https://github.com/fluix-dev/sway-borders/files/6658998/paru-output.txt)

Meson version: 0.58.1
Ninja version: 1.10.2

**Comment by fluix-dev** [comment]
I've just pulled upstream, please try again.

**Comment by Ziiga** [comment]
works perfectly, thank you!
