### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by shaunsingh** [fluix-dev/sway-borders#39]
### Please read the following before submitting:
Hi, loving this package on arch, Is it possible to use it on nixos as well?

### Please fill out the following:
- **Description:**
I would like to replace the sway package with sway-borders on nixos

**Comment by fluix-dev** [comment]
I won't personally do so because I don't use NixOS, but others are free to package it. I don't believe there's anything necessary from my side but do let me know if there is. As always though you can simply compile it from source on NixOS.

**Comment by shaunsingh** [comment]
I managed to have it replace the sway-unwrapped binary with sway-borders using an overlay, so it works now.
