### ISSUE TITLE
Create border image creation script

### ISSUE THREAD

**Issue by fluix-dev** [fluix-dev/sway-borders#4]
This script should have options for:
 - [ ] Color
 - [ ] Size
 - [ ] Rounded Borders
   - [ ] Radius
   - [ ] Offset
 - [ ] Shadows
   - [ ] Colour
   - [ ] Spread
   - [ ] Radius
   - [ ] Radius Offset
   - [ ] Grow
   - [ ] Offset

**Comment by nightly-brew** [comment]
Hi, it's not much, but I created a little script which implements some of the required features. 
My knowledge of cairo is rudimentary at best but I hope it helps anyway.
I successfully rigged an ansible role to autogenerate border images with that.

It's called [windowframer](https://github.com/nightly-brew/windowframer).

If anyone has ideas on how I could implement the other features (preferrably in a shape-agnostic way, like I tried to do with shadows), I would be happy to try my hand at it.

**Comment by fluix-dev** [comment]
I've begun the rework to use shaders, and with that I don't think a creation script will be necessary since it will be configured with config options. Here's a screenshot of the early work in progress allowing inner rounding.

![screenshot_20220206_225917](https://user-images.githubusercontent.com/52835679/152722576-2b806782-ef92-4d0a-bef8-d6f675fa4d64.png)
