### ISSUE TITLE
error installing from aur

### ISSUE THREAD

**Issue by errordotfiles** [fluix-dev/sway-borders#40]
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/ccK2opPD.ltrans1.ltrans.o: in function `handle_output_destroy':
<artificial>:(.text+0x8d03): undefined reference to `wlr_layer_surface_v1_close'
/usr/bin/ld: /tmp/ccK2opPD.ltrans1.ltrans.o: in function `handle_layer_shell_surface':
<artificial>:(.text+0x90a4): undefined reference to `wlr_layer_surface_v1_close'
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/ccK2opPD.ltrans7.ltrans.o: in function `arrange_layer.isra.0':
<artificial>:(.text+0x550c): undefined reference to `wlr_layer_surface_v1_close'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
==> ERROR: An error occurred in build(). The operation is about to be aborted...
error making: sway-borders-git

**Comment by fluix-dev** [comment]
Hm, could you try now?

**Comment by errordotfiles** [comment]
> Hm, could you try now?

now it's working, thank u
