### ISSUE TITLE
not able to compile it due to failed cast or using experimental wlroots api.

### ISSUE THREAD

**Issue by momofor** [fluix-dev/sway-borders#53]
### Please read the following before submitting:
- Make sure the issue is with one of the additional features of sway-borders or one which does not occur in sway upstream.

### Please fill out the following:
- **Sway Version:**
  - No not able to compile

- **Debug Log:**
  Can't compile due to : 
`ninja: Entering directory `build'
[456/542] Compiling C object sway/sway.p/server.c.o
FAILED: sway/sway.p/server.c.o 
ccache cc -Isway/sway.p -Isway -I../sway -Iinclude -I../include -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Iprotocols -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/json-c -I/usr/include/libevdev-1.0 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wno-missing-braces -Wundef -Wvla '-DSYSCONFDIR="//usr/local/etc"' '-DSWAY_VERSION="1.6-93501144 (" __DATE__ ", branch '"'"'master'"'"')"' -fmacro-prefix-map=../= -pthread -MD -MQ sway/sway.p/server.c.o -MF sway/sway.p/server.c.o.d -o sway/sway.p/server.c.o -c ../sway/server.c
../sway/server.c: In function ‘server_init’:
../sway/server.c:226:17: error: implicit declaration of function ‘wlr_headless_backend_create_with_renderer’; did you mean ‘wlr_headless_backend_create’? [-Werror=implicit-function-declaration]
  226 |                 wlr_headless_backend_create_with_renderer(server->wl_display,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 wlr_headless_backend_create
../sway/server.c:225:34: error: assignment to ‘struct wlr_backend *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  225 |         server->headless_backend =
      |                                  ^
cc1: all warnings being treated as errors
[465/542] Generating symbol file subprojects/wlroots/libwlroots.so.10.p/libwlroots.so.10.symbols
ninja: build stopped: subcommand failed.`
- **Configuration File:**
  - Please try to produce with the default configuration.
  - If you cannot reproduce with the default configuration, please try to find the minimal configuration to reproduce.
  - Upload the config to a pastebin such as gist.github.com.

- **Stack Trace:**
Can't compile to get the binary.

- **Description:**
  - download sway-borders-git from the aur or compile it with wlroots-git or normal subproject for wlroots.

**Comment by fluix-dev** [comment]
Should be fixed in https://github.com/fluix-dev/sway-borders/commit/ce47844e063a81d75a745c966c0fb7fd5183b1ea.

**Comment by momofor** [comment]
@fluix-dev thakns for the fix, it compiles just fine now :D.
