### ISSUE TITLE
wlroots needs updating 

### ISSUE THREAD

**Issue by NicolaiVdS** [fluix-dev/sway-borders#72]
wlroots-git ahs been updated resulting into swayborders failing
```
Dependency wlroots found: NO found 0.17.0-dev but need '<0.17.0' ; matched '>=0.16.0'
```

**Comment by fluix-dev** [comment]
Hm, not sure why I didn't get a notification for this. Fixed in https://github.com/fluix-dev/sway-borders/commit/c3ab09150bb9d64d43b8733ff0ea3a6d116e1398.
