### ISSUE TITLE
Unable to compile source and the Aur package doesn't install

### ISSUE THREAD

**Issue by danielerognini** [fluix-dev/sway-borders#74]
- Sway Version: 1.8-dev
- Wlroots version: 0.17.0-dev

### Description:
I wanted to try sway-borders, so the first thing I've tried was to get it from the Aur using `yay -S sway-borders-git` but that was giving me errors, I uploaded the console output [here](https://gist.github.com/danielerognini/8dfe9d36d1f2bf01893cd5b844bca590)

Since it wasn't working I tried to compile from source, I cloned the repo, and tried to build it using the commands found in the readme.md file  but the the `ninja -C build` command gives me [these](https://gist.github.com/danielerognini/c50d635395f826c680ccf682daeb3a3d) errors

**Comment by lindeMAX** [comment]
Is there some progress?
Couldn't build from source and AUR-package, too. :(

Logs can be found [here](https://gist.github.com/lindeMAX/50a38e89467fefeaf29da5fd0c898d43).

**Comment by lindeMAX** [comment]
I found out that there had bee some changes in [wlroots 0.17.0](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3527).
Mode events have been dropped.

**Comment by AnotherRandomGitHubAccount** [comment]
Yes, I have the same problem. is there a way to temporarily use an older version of wlroots and install it? or do we just need to wait until someone fixes this issue?

**Comment by fluix-dev** [comment]
Fixed in https://github.com/fluix-dev/sway-borders/commit/c9cbaf60307e35773785d84a3c28314d1e01208e.
