### ISSUE TITLE
Twin borders

### ISSUE THREAD

**Issue by plasticmae** [fluix-dev/sway-borders#76]
Hi! I'd like to request a double borders feature similar to what [2bwm](https://github.com/venam/2bwm) has. ![2bwm scrot](https://camo.githubusercontent.com/8a10a9d4787d49170b177a61d0f31d238a1b1699c0916cfc91575e2c2933a425/68747470733a2f2f76656e616d2e6e69786572732e6e65742f626c6f672f6173736574732f7363726f74732f31372e706e67)

**Comment by fluix-dev** [comment]
You can already do this. Just make your border images have two colours.
